### ISSUE TITLE
npm v8 breaks 😢

### ISSUE THREAD

**Issue by JBaczuk** [kodie/npm-gif#5]
😢

```
jbaczuk@Jordans-MacBook-Air test-gif % npm i axios
/Users/jbaczuk/n/lib/node_modules/npm-gif/node_modules/global-npm/index.js:37
      throw e
      ^

Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/Users/jbaczuk/n/lib/node_modules/npm/index.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.Module._load (/Users/jbaczuk/n/lib/node_modules/npm-gif/node_modules/mock-require/index.js:24:22)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/jbaczuk/n/lib/node_modules/npm-gif/node_modules/global-npm/index.js:29:15
    at Object.<anonymous> (/Users/jbaczuk/n/lib/node_modules/npm-gif/node_modules/global-npm/index.js:41:3)
```

**Comment by kodie** [comment]
Seems like this is related to this: https://github.com/dracupid/global-npm/issues/8
